<!doctype html public "-//W3C//DTD HTML 4.01 Transitional//EN">
<!--
  - @ORG_FQ@ @PKG_NAME@ Source Documentation Index.
  - @THIS_DATE@ @THIS_TIME@
  -->
<html>
  <head>
    <title>@ORG_INITIALS@ @PKG_NAME@-@PKG_VER@ PyDoc</title>

    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <meta http-equiv="Expires" content="0">
    <meta name="Author" content="@AUTHOR@">
    <meta name="Copyright" content="&copy; @THIS_YEAR@ @ORG_FQ@"
>
    <meta name="Description" content="Intelligent Systems and Robotics Technolog
ies Company">
    <meta name="keywords" lang="en-us"
content="RoadNarrows LLC, RoadNarrows Intelligent Systems LLC, RoadNarrows Robotics, intelligent systems, artificial neural networks, robotics">

    <link rel="icon" type="image/png" href="images/@FAVICON@">

<style type="text/css">
body, table, div, p, dl {
  font-family: Lucida Grande, Verdana, Geneva, Arial, sans-serif;
  font-size: 12px;
}

/* @group Heading Levels */

h1 {
  text-align: left;
  font-size: 150%;
  border-bottom: 3px solid #990000;
}

h1:before {
  content: url(images/@ORG_LOGO@);
  padding-right: 10px;
}

table.tbl1
{
  font-size: 14px;
  padding: 0 10px 5px 0;
}

table.tbl1 td
{
  text-align: left;
  padding: 0 5px 5px 0;
}

table.tbl1 td.num
{
  text-align: right;
}

table.tbl1 td.ref
{
  text-align: left;
}

table.tbl1 td.ref a
{
  font-weight: bold;
  text-decoration: underline;
}

table.tbl1 td.caption
{
  text-align: center;
  font-style: italic;
}
</style>
  </head>

  <body>
    <h1>
    @PKG_NAME@ v@PKG_VER@ Python Source Documentation
    </h1>
    @BRIEF@

    <h2>Product Description</h2>
    <p>
    @LONG_DESC@
    </p>

    <h2>Module Documentation</h2>
    <table class="tbl1">
      @MOD_LIST_ITER:"<tr><td class='ref'>\n<a href='%s'>%s</a></td></tr>" % (_ivar, _ivar)@
    </table>

    <h2>End User License Agreement</h2>
    <p>
    Click <a href="../EULA.html">here</a> to view the
    <b>@ORG_FQ@</b> <b>@PKG_NAME@</b> top-level EULA.
    </p>

    <br>
    <hr size="1">

    <p>
      The <b>@PKG_NAME@</b> python source documentation has been
      generated by pydoc.
      See
      <a href="http://docs.python.org/library/pydoc.html">docs.python.org/library/pydoc.html</a>
      for more details on pydoc.
    </p>

    <br>
    <hr size="1">

    <address>
      <div style="float:left">
          &copy;@THIS_YEAR@ @ORG_FQ@
          <br>
          <a href="@ORG_URL@">@ORG_URL@</a>
      </div>
      <div style="float:right">
    @THIS_DATE@
      </div>
    </address>
  </body>
</html>
