# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_bsDynaCore', [dirname(__file__)])
        except ImportError:
            import _bsDynaCore
            return _bsDynaCore
        if fp is not None:
            try:
                _mod = imp.load_module('_bsDynaCore', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _bsDynaCore = swig_import_helper()
    del swig_import_helper
else:
    import _bsDynaCore
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


DYNA_OK = _bsDynaCore.DYNA_OK
DYNA_ECODE_GEN = _bsDynaCore.DYNA_ECODE_GEN
DYNA_ECODE_SYS = _bsDynaCore.DYNA_ECODE_SYS
DYNA_ECODE_INTERNAL = _bsDynaCore.DYNA_ECODE_INTERNAL
DYNA_ECODE_BADEC = _bsDynaCore.DYNA_ECODE_BADEC
DYNA_ECODE_BAD_UNITS = _bsDynaCore.DYNA_ECODE_BAD_UNITS
DYNA_ECODE_BAD_VAL = _bsDynaCore.DYNA_ECODE_BAD_VAL
DYNA_ECODE_NO_SERVO = _bsDynaCore.DYNA_ECODE_NO_SERVO
DYNA_ECODE_BAD_DEV = _bsDynaCore.DYNA_ECODE_BAD_DEV
DYNA_ECODE_BADF = _bsDynaCore.DYNA_ECODE_BADF
DYNA_ECODE_ECOMM = _bsDynaCore.DYNA_ECODE_ECOMM
DYNA_ECODE_TX_FAIL = _bsDynaCore.DYNA_ECODE_TX_FAIL
DYNA_ECODE_RX_FAIL = _bsDynaCore.DYNA_ECODE_RX_FAIL
DYNA_ECODE_TX_ERROR = _bsDynaCore.DYNA_ECODE_TX_ERROR
DYNA_ECODE_RX_TIMEOUT = _bsDynaCore.DYNA_ECODE_RX_TIMEOUT
DYNA_ECODE_RX_BAD_PKT = _bsDynaCore.DYNA_ECODE_RX_BAD_PKT
DYNA_ECODE_ESERVO = _bsDynaCore.DYNA_ECODE_ESERVO
DYNA_ECODE_RSRC = _bsDynaCore.DYNA_ECODE_RSRC
DYNA_ECODE_NOT_SUPP = _bsDynaCore.DYNA_ECODE_NOT_SUPP
DYNA_ECODE_LINKED = _bsDynaCore.DYNA_ECODE_LINKED
DYNA_ECODE_SLAVE = _bsDynaCore.DYNA_ECODE_SLAVE
DYNA_ECODE_BOTSENSE = _bsDynaCore.DYNA_ECODE_BOTSENSE
DYNA_ECODE_PARSE = _bsDynaCore.DYNA_ECODE_PARSE
DYNA_ECODE_RUNTIME = _bsDynaCore.DYNA_ECODE_RUNTIME
DYNA_ECODE_NOEXEC = _bsDynaCore.DYNA_ECODE_NOEXEC
DYNA_ECODE_NUMOF = _bsDynaCore.DYNA_ECODE_NUMOF
DYNA_MODEL_NUM_GENERIC = _bsDynaCore.DYNA_MODEL_NUM_GENERIC
DYNA_FWVER_NA = _bsDynaCore.DYNA_FWVER_NA
DYNA_ID_NONE = _bsDynaCore.DYNA_ID_NONE
DYNA_ID_MIN = _bsDynaCore.DYNA_ID_MIN
DYNA_ID_MAX = _bsDynaCore.DYNA_ID_MAX
DYNA_ID_NUMOF = _bsDynaCore.DYNA_ID_NUMOF
DYNA_ID_BROADCAST = _bsDynaCore.DYNA_ID_BROADCAST
DYNA_ID_RESERVED = _bsDynaCore.DYNA_ID_RESERVED
DYNA_ID_MASK = _bsDynaCore.DYNA_ID_MASK
DYNA_MODE_SERVO = _bsDynaCore.DYNA_MODE_SERVO
DYNA_MODE_CONTINUOUS = _bsDynaCore.DYNA_MODE_CONTINUOUS
DYNA_LINK_NONE = _bsDynaCore.DYNA_LINK_NONE
DYNA_LINK_MASTER = _bsDynaCore.DYNA_LINK_MASTER
DYNA_LINK_SLAVE = _bsDynaCore.DYNA_LINK_SLAVE
DYNA_DIR_CW = _bsDynaCore.DYNA_DIR_CW
DYNA_DIR_NONE = _bsDynaCore.DYNA_DIR_NONE
DYNA_DIR_CCW = _bsDynaCore.DYNA_DIR_CCW
DYNA_CTL_METHOD_NONE = _bsDynaCore.DYNA_CTL_METHOD_NONE
DYNA_CTL_METHOD_COMPLIANCE = _bsDynaCore.DYNA_CTL_METHOD_COMPLIANCE
DYNA_CTL_METHOD_PID = _bsDynaCore.DYNA_CTL_METHOD_PID
DYNA_POS_MASK = _bsDynaCore.DYNA_POS_MASK
DYNA_POS_MIN_RAW = _bsDynaCore.DYNA_POS_MIN_RAW
DYNA_POS_MAX_RAW = _bsDynaCore.DYNA_POS_MAX_RAW
DYNA_POS_MODULO = _bsDynaCore.DYNA_POS_MODULO
DYNA_POS_MIN_DEG = _bsDynaCore.DYNA_POS_MIN_DEG
DYNA_POS_MAX_DEG = _bsDynaCore.DYNA_POS_MAX_DEG
DYNA_SPEED_MASK = _bsDynaCore.DYNA_SPEED_MASK
DYNA_SPEED_CONT_STOP = _bsDynaCore.DYNA_SPEED_CONT_STOP
DYNA_SPEED_MAX_NO_CTL = _bsDynaCore.DYNA_SPEED_MAX_NO_CTL
DYNA_SPEED_MIN_CTL = _bsDynaCore.DYNA_SPEED_MIN_CTL
DYNA_SPEED_MAX_CTL = _bsDynaCore.DYNA_SPEED_MAX_CTL
DYNA_SPEED_MIN_RAW = _bsDynaCore.DYNA_SPEED_MIN_RAW
DYNA_SPEED_MAX_RAW = _bsDynaCore.DYNA_SPEED_MAX_RAW
DYNA_SPEED_RES_RPM = _bsDynaCore.DYNA_SPEED_RES_RPM
DYNA_SPEED_RES_PCT = _bsDynaCore.DYNA_SPEED_RES_PCT
DYNA_SPEED_RES_PMIL = _bsDynaCore.DYNA_SPEED_RES_PMIL
DYNA_TORQUE_MASK = _bsDynaCore.DYNA_TORQUE_MASK
DYNA_TORQUE_MIN_RAW = _bsDynaCore.DYNA_TORQUE_MIN_RAW
DYNA_TORQUE_MAX_RAW = _bsDynaCore.DYNA_TORQUE_MAX_RAW
DYNA_TORQUE_RES_PCT = _bsDynaCore.DYNA_TORQUE_RES_PCT
DYNA_TORQUE_RES_PMIL = _bsDynaCore.DYNA_TORQUE_RES_PMIL
DYNA_TEMP_MIN_RAW = _bsDynaCore.DYNA_TEMP_MIN_RAW
DYNA_TEMP_MAX_RAW = _bsDynaCore.DYNA_TEMP_MAX_RAW
DYNA_TEMP_MIN_C = _bsDynaCore.DYNA_TEMP_MIN_C
DYNA_TEMP_MAX_C = _bsDynaCore.DYNA_TEMP_MAX_C
DYNA_TEMP_RES_C = _bsDynaCore.DYNA_TEMP_RES_C
DYNA_VOLT_MIN_RAW = _bsDynaCore.DYNA_VOLT_MIN_RAW
DYNA_VOLT_MAX_RAW = _bsDynaCore.DYNA_VOLT_MAX_RAW
DYNA_VOLT_RES_V = _bsDynaCore.DYNA_VOLT_RES_V
DYNA_EEPROM_MIN_ADDR = _bsDynaCore.DYNA_EEPROM_MIN_ADDR
DYNA_EEPROM_MAX_ADDR = _bsDynaCore.DYNA_EEPROM_MAX_ADDR
DYNA_RAM_MIN_ADDR = _bsDynaCore.DYNA_RAM_MIN_ADDR
DYNA_RAM_MAX_ADDR = _bsDynaCore.DYNA_RAM_MAX_ADDR
DYNA_MEM_MAX_SIZ = _bsDynaCore.DYNA_MEM_MAX_SIZ
DYNA_ADDR_MODEL_NUM_LSB = _bsDynaCore.DYNA_ADDR_MODEL_NUM_LSB
DYNA_ADDR_MODEL_NUM_MSB = _bsDynaCore.DYNA_ADDR_MODEL_NUM_MSB
DYNA_ADDR_MODEL_NUM_MASK = _bsDynaCore.DYNA_ADDR_MODEL_NUM_MASK
DYNA_ADDR_FWVER = _bsDynaCore.DYNA_ADDR_FWVER
DYNA_ADDR_FWVER_MASK = _bsDynaCore.DYNA_ADDR_FWVER_MASK
DYNA_ADDR_ID = _bsDynaCore.DYNA_ADDR_ID
DYNA_ADDR_ID_MASK = _bsDynaCore.DYNA_ADDR_ID_MASK
DYNA_ADDR_BAUD_RATE = _bsDynaCore.DYNA_ADDR_BAUD_RATE
DYNA_ADDR_BAUD_RATE_MASK = _bsDynaCore.DYNA_ADDR_BAUD_RATE_MASK
DYNA_BAUDNUM_1000000 = _bsDynaCore.DYNA_BAUDNUM_1000000
DYNA_BAUDNUM_500000 = _bsDynaCore.DYNA_BAUDNUM_500000
DYNA_BAUDNUM_400000 = _bsDynaCore.DYNA_BAUDNUM_400000
DYNA_BAUDNUM_250000 = _bsDynaCore.DYNA_BAUDNUM_250000
DYNA_BAUDNUM_200000 = _bsDynaCore.DYNA_BAUDNUM_200000
DYNA_BAUDNUM_115200 = _bsDynaCore.DYNA_BAUDNUM_115200
DYNA_BAUDNUM_57600 = _bsDynaCore.DYNA_BAUDNUM_57600
DYNA_BAUDNUM_19200 = _bsDynaCore.DYNA_BAUDNUM_19200
DYNA_BAUDNUM_9600 = _bsDynaCore.DYNA_BAUDNUM_9600
DYNA_BAUDNUM_EXT_2250000 = _bsDynaCore.DYNA_BAUDNUM_EXT_2250000
DYNA_BAUDNUM_EXT_2500000 = _bsDynaCore.DYNA_BAUDNUM_EXT_2500000
DYNA_BAUDNUM_EXT_3000000 = _bsDynaCore.DYNA_BAUDNUM_EXT_3000000
DYNA_BAUDNUM_NUMOF = _bsDynaCore.DYNA_BAUDNUM_NUMOF
DYNA_BAUDNUM_DFT = _bsDynaCore.DYNA_BAUDNUM_DFT
DYNA_BAUDRATE_DFT = _bsDynaCore.DYNA_BAUDRATE_DFT
DYNA_ADDR_T_RET_DELAY = _bsDynaCore.DYNA_ADDR_T_RET_DELAY
DYNA_ADDR_T_RET_DELAY_MASK = _bsDynaCore.DYNA_ADDR_T_RET_DELAY_MASK
DYNA_T_RET_DELAY_MIN_RAW = _bsDynaCore.DYNA_T_RET_DELAY_MIN_RAW
DYNA_T_RET_DELAY_MAX_RAW = _bsDynaCore.DYNA_T_RET_DELAY_MAX_RAW
DYNA_T_RET_DELAY_DFT_RAW = _bsDynaCore.DYNA_T_RET_DELAY_DFT_RAW
DYNA_T_RET_DELAY_RES_USEC = _bsDynaCore.DYNA_T_RET_DELAY_RES_USEC
DYNA_T_RET_DELAY_MIN_USEC = _bsDynaCore.DYNA_T_RET_DELAY_MIN_USEC
DYNA_T_RET_DELAY_MAX_USEC = _bsDynaCore.DYNA_T_RET_DELAY_MAX_USEC
DYNA_T_RET_DELAY_DFT_USEC = _bsDynaCore.DYNA_T_RET_DELAY_DFT_USEC
DYNA_ADDR_LIM_CW_LSB = _bsDynaCore.DYNA_ADDR_LIM_CW_LSB
DYNA_ADDR_LIM_CW_MSB = _bsDynaCore.DYNA_ADDR_LIM_CW_MSB
DYNA_ADDR_LIM_CW_MASK = _bsDynaCore.DYNA_ADDR_LIM_CW_MASK
DYNA_CW_POS_CONT_MODE = _bsDynaCore.DYNA_CW_POS_CONT_MODE
DYNA_ADDR_LIM_CCW_LSB = _bsDynaCore.DYNA_ADDR_LIM_CCW_LSB
DYNA_ADDR_LIM_CCW_MSB = _bsDynaCore.DYNA_ADDR_LIM_CCW_MSB
DYNA_ADDR_LIM_CCW_MASK = _bsDynaCore.DYNA_ADDR_LIM_CCW_MASK
DYNA_CCW_POS_CONT_MODE = _bsDynaCore.DYNA_CCW_POS_CONT_MODE
DYNA_ADDR_RESERVED_1 = _bsDynaCore.DYNA_ADDR_RESERVED_1
DYNA_ADDR_LIM_TEMP_MAX = _bsDynaCore.DYNA_ADDR_LIM_TEMP_MAX
DYNA_ADDR_LIM_TEMP_MASK = _bsDynaCore.DYNA_ADDR_LIM_TEMP_MASK
DYNA_LIM_TEMP_MIN_C = _bsDynaCore.DYNA_LIM_TEMP_MIN_C
DYNA_LIM_TEMP_MAX_C = _bsDynaCore.DYNA_LIM_TEMP_MAX_C
DYNA_LIM_TEMP_DFT_C = _bsDynaCore.DYNA_LIM_TEMP_DFT_C
DYNA_LIM_TEMP_RES_C = _bsDynaCore.DYNA_LIM_TEMP_RES_C
DYNA_ADDR_LIM_VOLT_MIN = _bsDynaCore.DYNA_ADDR_LIM_VOLT_MIN
DYNA_ADDR_LIM_VOLT_MIN_MASK = _bsDynaCore.DYNA_ADDR_LIM_VOLT_MIN_MASK
DYNA_LIM_VOLT_MIN_MIN_RAW = _bsDynaCore.DYNA_LIM_VOLT_MIN_MIN_RAW
DYNA_LIM_VOLT_MIN_MAX_RAW = _bsDynaCore.DYNA_LIM_VOLT_MIN_MAX_RAW
DYNA_LIM_VOLT_MIN_DFT_RAW = _bsDynaCore.DYNA_LIM_VOLT_MIN_DFT_RAW
DYNA_LIM_VOLT_MIN_RES_V = _bsDynaCore.DYNA_LIM_VOLT_MIN_RES_V
DYNA_LIM_VOLT_MIN_MIN_V = _bsDynaCore.DYNA_LIM_VOLT_MIN_MIN_V
DYNA_ADDR_LIM_VOLT_MAX = _bsDynaCore.DYNA_ADDR_LIM_VOLT_MAX
DYNA_ADDR_LIM_VOLT_MAX_MASK = _bsDynaCore.DYNA_ADDR_LIM_VOLT_MAX_MASK
DYNA_LIM_VOLT_MAX_MIN_RAW = _bsDynaCore.DYNA_LIM_VOLT_MAX_MIN_RAW
DYNA_LIM_VOLT_MAX_MAX_RAW = _bsDynaCore.DYNA_LIM_VOLT_MAX_MAX_RAW
DYNA_LIM_VOLT_MAX_DFT_RAW = _bsDynaCore.DYNA_LIM_VOLT_MAX_DFT_RAW
DYNA_LIM_VOLT_MAX_RES_V = _bsDynaCore.DYNA_LIM_VOLT_MAX_RES_V
DYNA_LIM_VOLT_MAX_MIN_V = _bsDynaCore.DYNA_LIM_VOLT_MAX_MIN_V
DYNA_ADDR_LIM_TORQUE_MAX_ON_LSB = _bsDynaCore.DYNA_ADDR_LIM_TORQUE_MAX_ON_LSB
DYNA_ADDR_LIM_TORQUE_MAX_ON_MSB = _bsDynaCore.DYNA_ADDR_LIM_TORQUE_MAX_ON_MSB
DYNA_ADDR_LIM_TORQUE_MAX_ON_MASK = _bsDynaCore.DYNA_ADDR_LIM_TORQUE_MAX_ON_MASK
DYNA_LIM_TORQUE_MAX_ON_DFT_RAW = _bsDynaCore.DYNA_LIM_TORQUE_MAX_ON_DFT_RAW
DYNA_ADDR_SRL = _bsDynaCore.DYNA_ADDR_SRL
DYNA_ADDR_SRL_MASK = _bsDynaCore.DYNA_ADDR_SRL_MASK
DYNA_SRL_RET_NONE = _bsDynaCore.DYNA_SRL_RET_NONE
DYNA_SRL_RET_READ = _bsDynaCore.DYNA_SRL_RET_READ
DYNA_SRL_RET_ALL = _bsDynaCore.DYNA_SRL_RET_ALL
DYNA_SRL_RET_DFT = _bsDynaCore.DYNA_SRL_RET_DFT
DYNA_ADDR_ALARM_LED = _bsDynaCore.DYNA_ADDR_ALARM_LED
DYNA_ADDR_ALARM_LED_MASK = _bsDynaCore.DYNA_ADDR_ALARM_LED_MASK
DYNA_ADDR_ALARM_SHUTDOWN = _bsDynaCore.DYNA_ADDR_ALARM_SHUTDOWN
DYNA_ADDR_ALARM_SHUTDOWN_MASK = _bsDynaCore.DYNA_ADDR_ALARM_SHUTDOWN_MASK
DYNA_ALARM_NONE = _bsDynaCore.DYNA_ALARM_NONE
DYNA_ALARM_VOLTAGE = _bsDynaCore.DYNA_ALARM_VOLTAGE
DYNA_ALARM_ANGLE = _bsDynaCore.DYNA_ALARM_ANGLE
DYNA_ALARM_TEMP = _bsDynaCore.DYNA_ALARM_TEMP
DYNA_ALARM_CMD_RANGE = _bsDynaCore.DYNA_ALARM_CMD_RANGE
DYNA_ALARM_CHECKSUM = _bsDynaCore.DYNA_ALARM_CHECKSUM
DYNA_ALARM_LOAD = _bsDynaCore.DYNA_ALARM_LOAD
DYNA_ALARM_INSTRUCTION = _bsDynaCore.DYNA_ALARM_INSTRUCTION
DYNA_ALARM_DFT = _bsDynaCore.DYNA_ALARM_DFT
DYNA_ADDR_TORQUE_EN = _bsDynaCore.DYNA_ADDR_TORQUE_EN
DYNA_ADDR_TORQUE_EN_MASK = _bsDynaCore.DYNA_ADDR_TORQUE_EN_MASK
DYNA_TORQUE_EN_OFF = _bsDynaCore.DYNA_TORQUE_EN_OFF
DYNA_TORQUE_EN_ON = _bsDynaCore.DYNA_TORQUE_EN_ON
DYNA_TORQUE_EN_DFT = _bsDynaCore.DYNA_TORQUE_EN_DFT
DYNA_ADDR_LED = _bsDynaCore.DYNA_ADDR_LED
DYNA_ADDR_LED_MASK = _bsDynaCore.DYNA_ADDR_LED_MASK
DYNA_LED_OFF = _bsDynaCore.DYNA_LED_OFF
DYNA_LED_ON = _bsDynaCore.DYNA_LED_ON
DYNA_ADDR_CW_COMP_MARGIN = _bsDynaCore.DYNA_ADDR_CW_COMP_MARGIN
DYNA_ADDR_CW_COMP_MASK = _bsDynaCore.DYNA_ADDR_CW_COMP_MASK
DYNA_COMP_MARGIN_MIN_RAW = _bsDynaCore.DYNA_COMP_MARGIN_MIN_RAW
DYNA_COMP_MARGIN_MAX_RAW = _bsDynaCore.DYNA_COMP_MARGIN_MAX_RAW
DYNA_COMP_MARGIN_DFT_RAW = _bsDynaCore.DYNA_COMP_MARGIN_DFT_RAW
DYNA_ADDR_CCW_COMP_MARGIN = _bsDynaCore.DYNA_ADDR_CCW_COMP_MARGIN
DYNA_ADDR_CCW_COMP_MASK = _bsDynaCore.DYNA_ADDR_CCW_COMP_MASK
DYNA_ADDR_CW_COMP_SLOPE = _bsDynaCore.DYNA_ADDR_CW_COMP_SLOPE
DYNA_ADDR_CW_COMP_SLOPE_MASK = _bsDynaCore.DYNA_ADDR_CW_COMP_SLOPE_MASK
DYNA_COMP_SLOPE_TORQUE_1 = _bsDynaCore.DYNA_COMP_SLOPE_TORQUE_1
DYNA_COMP_SLOPE_TORQUE_2 = _bsDynaCore.DYNA_COMP_SLOPE_TORQUE_2
DYNA_COMP_SLOPE_TORQUE_3 = _bsDynaCore.DYNA_COMP_SLOPE_TORQUE_3
DYNA_COMP_SLOPE_TORQUE_4 = _bsDynaCore.DYNA_COMP_SLOPE_TORQUE_4
DYNA_COMP_SLOPE_TORQUE_5 = _bsDynaCore.DYNA_COMP_SLOPE_TORQUE_5
DYNA_COMP_SLOPE_TORQUE_6 = _bsDynaCore.DYNA_COMP_SLOPE_TORQUE_6
DYNA_COMP_SLOPE_TORQUE_7 = _bsDynaCore.DYNA_COMP_SLOPE_TORQUE_7
DYNA_COMP_SLOPE_TORQUE_DFT = _bsDynaCore.DYNA_COMP_SLOPE_TORQUE_DFT
DYNA_ADDR_CCW_COMP_SLOPE = _bsDynaCore.DYNA_ADDR_CCW_COMP_SLOPE
DYNA_ADDR_CCW_COMP_SLOPE_MASK = _bsDynaCore.DYNA_ADDR_CCW_COMP_SLOPE_MASK
DYNA_ADDR_P_GAIN = _bsDynaCore.DYNA_ADDR_P_GAIN
DYNA_ADDR_P_GAIN_MASK = _bsDynaCore.DYNA_ADDR_P_GAIN_MASK
DYNA_P_GAIN_MIN_RAW = _bsDynaCore.DYNA_P_GAIN_MIN_RAW
DYNA_P_GAIN_MAX_RAW = _bsDynaCore.DYNA_P_GAIN_MAX_RAW
DYNA_P_GAIN_DFT = _bsDynaCore.DYNA_P_GAIN_DFT
DYNA_ADDR_I_GAIN = _bsDynaCore.DYNA_ADDR_I_GAIN
DYNA_ADDR_I_GAIN_MASK = _bsDynaCore.DYNA_ADDR_I_GAIN_MASK
DYNA_I_GAIN_MIN_RAW = _bsDynaCore.DYNA_I_GAIN_MIN_RAW
DYNA_I_GAIN_MAX_RAW = _bsDynaCore.DYNA_I_GAIN_MAX_RAW
DYNA_I_GAIN_DFT = _bsDynaCore.DYNA_I_GAIN_DFT
DYNA_ADDR_D_GAIN = _bsDynaCore.DYNA_ADDR_D_GAIN
DYNA_ADDR_D_GAIN_MASK = _bsDynaCore.DYNA_ADDR_D_GAIN_MASK
DYNA_D_GAIN_MIN_RAW = _bsDynaCore.DYNA_D_GAIN_MIN_RAW
DYNA_D_GAIN_MAX_RAW = _bsDynaCore.DYNA_D_GAIN_MAX_RAW
DYNA_D_GAIN_DFT = _bsDynaCore.DYNA_D_GAIN_DFT
DYNA_ADDR_PID_RESERVED = _bsDynaCore.DYNA_ADDR_PID_RESERVED
DYNA_ADDR_GOAL_POS_LSB = _bsDynaCore.DYNA_ADDR_GOAL_POS_LSB
DYNA_ADDR_GOAL_POS_MSB = _bsDynaCore.DYNA_ADDR_GOAL_POS_MSB
DYNA_ADDR_GOAL_POS_MASK = _bsDynaCore.DYNA_ADDR_GOAL_POS_MASK
DYNA_ADDR_GOAL_SPEED_LSB = _bsDynaCore.DYNA_ADDR_GOAL_SPEED_LSB
DYNA_ADDR_GOAL_SPEED_MSB = _bsDynaCore.DYNA_ADDR_GOAL_SPEED_MSB
DYNA_ADDR_GOAL_SPEED_MASK = _bsDynaCore.DYNA_ADDR_GOAL_SPEED_MASK
DYNA_GOAL_SPEED_MAG_MASK = _bsDynaCore.DYNA_GOAL_SPEED_MAG_MASK
DYNA_GOAL_SPEED_MAG_SHIFT = _bsDynaCore.DYNA_GOAL_SPEED_MAG_SHIFT
DYNA_GOAL_SPEED_DIR_MASK = _bsDynaCore.DYNA_GOAL_SPEED_DIR_MASK
DYNA_GOAL_SPEED_DIR_SHIFT = _bsDynaCore.DYNA_GOAL_SPEED_DIR_SHIFT
DYNA_GOAL_SPEED_DIR_CCW = _bsDynaCore.DYNA_GOAL_SPEED_DIR_CCW
DYNA_ADDR_LIM_TORQUE_MAX_LSB = _bsDynaCore.DYNA_ADDR_LIM_TORQUE_MAX_LSB
DYNA_ADDR_LIM_TORQUE_MAX_MSB = _bsDynaCore.DYNA_ADDR_LIM_TORQUE_MAX_MSB
DYNA_ADDR_LIM_TORQUE_MAX_MASK = _bsDynaCore.DYNA_ADDR_LIM_TORQUE_MAX_MASK
DYNA_LIM_TORQUE_MAX_ALARMED = _bsDynaCore.DYNA_LIM_TORQUE_MAX_ALARMED
DYNA_ADDR_CUR_POS_LSB = _bsDynaCore.DYNA_ADDR_CUR_POS_LSB
DYNA_ADDR_CUR_POS_MSB = _bsDynaCore.DYNA_ADDR_CUR_POS_MSB
DYNA_ADDR_CUR_POS_MASK = _bsDynaCore.DYNA_ADDR_CUR_POS_MASK
DYNA_ADDR_CUR_SPEED_LSB = _bsDynaCore.DYNA_ADDR_CUR_SPEED_LSB
DYNA_ADDR_CUR_SPEED_MSB = _bsDynaCore.DYNA_ADDR_CUR_SPEED_MSB
DYNA_ADDR_CUR_SPEED_MASK = _bsDynaCore.DYNA_ADDR_CUR_SPEED_MASK
DYNA_CUR_SPEED_MAG_MASK = _bsDynaCore.DYNA_CUR_SPEED_MAG_MASK
DYNA_CUR_SPEED_MAG_SHIFT = _bsDynaCore.DYNA_CUR_SPEED_MAG_SHIFT
DYNA_CUR_SPEED_DIR_MASK = _bsDynaCore.DYNA_CUR_SPEED_DIR_MASK
DYNA_CUR_SPEED_DIR_SHIFT = _bsDynaCore.DYNA_CUR_SPEED_DIR_SHIFT
DYNA_CUR_SPEED_DIR_CCW = _bsDynaCore.DYNA_CUR_SPEED_DIR_CCW
DYNA_CUR_SPEED_DIR_CW = _bsDynaCore.DYNA_CUR_SPEED_DIR_CW
DYNA_ADDR_CUR_LOAD_LSB = _bsDynaCore.DYNA_ADDR_CUR_LOAD_LSB
DYNA_ADDR_CUR_LOAD_MSB = _bsDynaCore.DYNA_ADDR_CUR_LOAD_MSB
DYNA_ADDR_CUR_LOAD_MASK = _bsDynaCore.DYNA_ADDR_CUR_LOAD_MASK
DYNA_CUR_LOAD_MAG_MASK = _bsDynaCore.DYNA_CUR_LOAD_MAG_MASK
DYNA_CUR_LOAD_MAG_SHIFT = _bsDynaCore.DYNA_CUR_LOAD_MAG_SHIFT
DYNA_CUR_LOAD_MAG_MIN = _bsDynaCore.DYNA_CUR_LOAD_MAG_MIN
DYNA_CUR_LOAD_MAG_MAX = _bsDynaCore.DYNA_CUR_LOAD_MAG_MAX
DYNA_CUR_LOAD_DIR_MASK = _bsDynaCore.DYNA_CUR_LOAD_DIR_MASK
DYNA_CUR_LOAD_DIR_SHIFT = _bsDynaCore.DYNA_CUR_LOAD_DIR_SHIFT
DYNA_CUR_LOAD_DIR_CCW = _bsDynaCore.DYNA_CUR_LOAD_DIR_CCW
DYNA_CUR_LOAD_DIR_CW = _bsDynaCore.DYNA_CUR_LOAD_DIR_CW
DYNA_CUR_LOAD_RES_PCT = _bsDynaCore.DYNA_CUR_LOAD_RES_PCT
DYNA_CUR_LOAD_RES_PMIL = _bsDynaCore.DYNA_CUR_LOAD_RES_PMIL
DYNA_ADDR_CUR_VOLT = _bsDynaCore.DYNA_ADDR_CUR_VOLT
DYNA_ADDR_CUR_VOLT_MASK = _bsDynaCore.DYNA_ADDR_CUR_VOLT_MASK
DYNA_CUR_VOLT_RES_V = _bsDynaCore.DYNA_CUR_VOLT_RES_V
DYNA_ADDR_CUR_TEMP_C = _bsDynaCore.DYNA_ADDR_CUR_TEMP_C
DYNA_ADDR_CUR_TEMP_MASK = _bsDynaCore.DYNA_ADDR_CUR_TEMP_MASK
DYNA_CUR_TEMP_RES_C = _bsDynaCore.DYNA_CUR_TEMP_RES_C
DYNA_ADDR_REG_INSTR = _bsDynaCore.DYNA_ADDR_REG_INSTR
DYNA_ADDR_REG_INSTR_MASK = _bsDynaCore.DYNA_ADDR_REG_INSTR_MASK
DYBA_REG_INSTR_NO_WRITE = _bsDynaCore.DYBA_REG_INSTR_NO_WRITE
DYBA_REG_INSTR_HAS_WRITE = _bsDynaCore.DYBA_REG_INSTR_HAS_WRITE
DYNA_ADDR_RESERVED_2 = _bsDynaCore.DYNA_ADDR_RESERVED_2
DYNA_ADDR_IS_MOVING = _bsDynaCore.DYNA_ADDR_IS_MOVING
DYNA_ADDR_IS_MOVING_MASK = _bsDynaCore.DYNA_ADDR_IS_MOVING_MASK
DYNA_IS_NOT_MOVING = _bsDynaCore.DYNA_IS_NOT_MOVING
DYNA_IS_MOVING = _bsDynaCore.DYNA_IS_MOVING
DYNA_ADDR_EEPROM_LOCK = _bsDynaCore.DYNA_ADDR_EEPROM_LOCK
DYNA_ADDR_EEPROM_LOCK_MASK = _bsDynaCore.DYNA_ADDR_EEPROM_LOCK_MASK
DYNA_EEPROM_UNLOCKED = _bsDynaCore.DYNA_EEPROM_UNLOCKED
DYNA_EEPROM_LOCKED = _bsDynaCore.DYNA_EEPROM_LOCKED
DYNA_EEPROM_LOCK_DFT = _bsDynaCore.DYNA_EEPROM_LOCK_DFT
DYNA_ADDR_PUNCH_LSB = _bsDynaCore.DYNA_ADDR_PUNCH_LSB
DYNA_ADDR_PUNCH_MSB = _bsDynaCore.DYNA_ADDR_PUNCH_MSB
BS_DYNA_SERVER_MOD = _bsDynaCore.BS_DYNA_SERVER_MOD
BS_DYNA_CLIENT_LIB = _bsDynaCore.BS_DYNA_CLIENT_LIB

def bsDynaGetMsgName(*args):
  return _bsDynaCore.bsDynaGetMsgName(*args)
bsDynaGetMsgName = _bsDynaCore.bsDynaGetMsgName

def bsDynaOpen(*args):
  return _bsDynaCore.bsDynaOpen(*args)
bsDynaOpen = _bsDynaCore.bsDynaOpen

def bsDynaClose(*args):
  return _bsDynaCore.bsDynaClose(*args)
bsDynaClose = _bsDynaCore.bsDynaClose

def bsDynaSetBaudRate(*args):
  return _bsDynaCore.bsDynaSetBaudRate(*args)
bsDynaSetBaudRate = _bsDynaCore.bsDynaSetBaudRate

def bsDynaRead8(*args):
  return _bsDynaCore.bsDynaRead8(*args)
bsDynaRead8 = _bsDynaCore.bsDynaRead8

def bsDynaWrite8(*args):
  return _bsDynaCore.bsDynaWrite8(*args)
bsDynaWrite8 = _bsDynaCore.bsDynaWrite8

def bsDynaRead16(*args):
  return _bsDynaCore.bsDynaRead16(*args)
bsDynaRead16 = _bsDynaCore.bsDynaRead16

def bsDynaWrite16(*args):
  return _bsDynaCore.bsDynaWrite16(*args)
bsDynaWrite16 = _bsDynaCore.bsDynaWrite16

def bsDynaSyncWrite(*args):
  return _bsDynaCore.bsDynaSyncWrite(*args)
bsDynaSyncWrite = _bsDynaCore.bsDynaSyncWrite

def bsDynaPing(*args):
  return _bsDynaCore.bsDynaPing(*args)
bsDynaPing = _bsDynaCore.bsDynaPing

def bsDynaReset(*args):
  return _bsDynaCore.bsDynaReset(*args)
bsDynaReset = _bsDynaCore.bsDynaReset

def bsDynaSetHalfDuplexCtl(*args):
  return _bsDynaCore.bsDynaSetHalfDuplexCtl(*args)
bsDynaSetHalfDuplexCtl = _bsDynaCore.bsDynaSetHalfDuplexCtl

def new_uintArray(*args):
  return _bsDynaCore.new_uintArray(*args)
new_uintArray = _bsDynaCore.new_uintArray

def delete_uintArray(*args):
  return _bsDynaCore.delete_uintArray(*args)
delete_uintArray = _bsDynaCore.delete_uintArray

def uintArray_getitem(*args):
  return _bsDynaCore.uintArray_getitem(*args)
uintArray_getitem = _bsDynaCore.uintArray_getitem

def uintArray_setitem(*args):
  return _bsDynaCore.uintArray_setitem(*args)
uintArray_setitem = _bsDynaCore.uintArray_setitem

def new_boolArray(*args):
  return _bsDynaCore.new_boolArray(*args)
new_boolArray = _bsDynaCore.new_boolArray

def delete_boolArray(*args):
  return _bsDynaCore.delete_boolArray(*args)
delete_boolArray = _bsDynaCore.delete_boolArray

def boolArray_getitem(*args):
  return _bsDynaCore.boolArray_getitem(*args)
boolArray_getitem = _bsDynaCore.boolArray_getitem

def boolArray_setitem(*args):
  return _bsDynaCore.boolArray_setitem(*args)
boolArray_setitem = _bsDynaCore.boolArray_setitem

def new_intp():
  return _bsDynaCore.new_intp()
new_intp = _bsDynaCore.new_intp

def copy_intp(*args):
  return _bsDynaCore.copy_intp(*args)
copy_intp = _bsDynaCore.copy_intp

def delete_intp(*args):
  return _bsDynaCore.delete_intp(*args)
delete_intp = _bsDynaCore.delete_intp

def intp_assign(*args):
  return _bsDynaCore.intp_assign(*args)
intp_assign = _bsDynaCore.intp_assign

def intp_value(*args):
  return _bsDynaCore.intp_value(*args)
intp_value = _bsDynaCore.intp_value

def new_uintp():
  return _bsDynaCore.new_uintp()
new_uintp = _bsDynaCore.new_uintp

def copy_uintp(*args):
  return _bsDynaCore.copy_uintp(*args)
copy_uintp = _bsDynaCore.copy_uintp

def delete_uintp(*args):
  return _bsDynaCore.delete_uintp(*args)
delete_uintp = _bsDynaCore.delete_uintp

def uintp_assign(*args):
  return _bsDynaCore.uintp_assign(*args)
uintp_assign = _bsDynaCore.uintp_assign

def uintp_value(*args):
  return _bsDynaCore.uintp_value(*args)
uintp_value = _bsDynaCore.uintp_value
"""
BotSense Dynamixel Python Core Interface.
"""

## \file 
## \package BotSense.Dynamixel.bsDynaCore
##
## \brief BotSense swigged Dynamixel Python core interface module.
##
## \author Robin Knight (robin.knight@roadnarrows.com)
##  
## \par Copyright:
##   (C) 2012-2015.  RoadNarrows LLC.\n
##   (http://www.roadnarrows.com)\n
##   All Rights Reserved
##


# This file is compatible with both classic and new-style classes.


