#!/bin/bash
#
# Script: eudoxus_openni2
#

## \file
##
## $LastChangedDate$
## $Rev$
## 
## \brief Script providing service to monitor user push button events to
## launch or kill openni2 nodes.
##
## This script is used by init.d eudoxus_shutter service.
##
## \author: Robin Knight (robin.knight@roadnarrows.com)
## 
## \par Copyright:
##   (C) 2016.  RoadNarrows LLC.
##   (http://www.roadnarrows.com)
##   All Rights Reserved

#
# @EulaBegin@
# @EulaEnd@
#

# Exported GPIO numbers.
declare -r gpio_led=18      # blue user LED output GPIO
declare -r gpio_bttn=19     # user push button input GPIO

# GPIO values.
# For the user button, the released state is 1; pushed state is 0.
# For the user LED, the LED off state is 0, the on state is 1.
declare -i old_button=1   # old push button state
declare -i button=1       # current push button state
declare -i led=0          # current led state

# Times
declare -i t_led=$(date +%s)    # last led state change time
declare -i t_cur                # current time
declare -i t_diff               # time difference

# Some user defined state variables
declare -i action_state=0   # action state, 0 is not running, 1 is running 
declare -i action_pid=0     # action process PID

#
# Hook to test if user defined action is running.
#
# Return 0 or 1.
#
action_running()
{
  action_state=0
  if [ ${action_pid} -gt 0 ]
  then
    kill -0 ${action_pid} >/dev/null 2>&1
    if [ $? -eq 0 ]
    then
      action_state=1
    else
      action_pid=0
    fi
  fi

  echo ${action_state}
}

#
# Hook to start user defined action function.
#
action_start()
{
  echo
  echo "*** Started on $(date) ***"
  roslaunch openni2_launch openni2.launch &
  action_pid=$!
  action_state=1
  sleep 1
}

#
# Hook to stop user defined action function.
#
action_stop()
{
  echo
  echo "*** Stopped on $(date) ***"
  kill ${action_pid} >/dev/null 2>&1
  action_pid=0
  action_state=0
  sleep 1
}

#
# Set LED
#   
# If not action_state, thenthe LED should be solid on
# If action_state, then the LED should slowly blink
#
setled()
{
  if [ ${action_state} -eq 0 ]
  then
    if [ ${led} -eq 0 ]
    then
      led=1
      gpiowrite ${gpio_led} ${led}
      t_led=${t_cur}
    fi
  else
    t_cur=$(date +%s)
    t_diff=${t_cur}-${t_led}
    if [ ${t_diff} -ge 1 ]
    then
      if [ ${led} -eq 0 ]
      then
        led=1
      else
        led=0
      fi
      gpiowrite ${gpio_led} ${led}
      t_led=${t_cur}
    fi
  fi
}

#
# Block-wait on user push button events.
#
while :
do
  gpionotify --timeout=1.0 --monitor ${gpio_bttn} | \
  while read button
  do
    case ${button}
    in
      0) #echo "Button is in the pushed state"
          ;;
      1) #echo "Button is in the released state"
          # pushed --> released
          if [ ${old_button} -eq 0 ]
          then
            action_state=$(action_running)
            if [ ${action_state} -eq 1 ] # currently action_state
            then
              action_stop
            else # currently not action_state
              action_start
            fi
          fi
          ;;
     -1|*)  echo "Error"
            exit 4;
          ;;
    esac
    old_button=${button}
    setled
  done
done

exit 0
