#!/bin/sh

# DHP: use as boilerplate
# This scriopt will remove old files before installing new ones

# set -e
# Automatically added by dh_installdocs
# if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/parted ]; then
#   rm -f /usr/doc/parted
# fi
# End automatically added section
