#! /bin/sh
################################################################################
#
# File:     prod_make_dist
#
# Version:
#   $LastChangedDate$
#   $Rev$
#
# Description:
#   Make product distribution files and tarballs.
#
# Author: Robin Knight (robin.knight@roadnarrows.com)
#
# Copyright (C) 2009.  RoadNarrows LLC.
# All Rights Reserved
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that
# (1) The above copyright notice and the following two paragraphs
# appear in all copies of the source code and (2) redistributions
# including binaries reproduces these notices in the supporting
# documentation.   Substantial modifications to this software may be
# copyrighted by their authors and need not follow the licensing terms
# described here, provided that the new terms are clearly indicated in
# all files where they apply.
#
# IN NO EVENT SHALL THE AUTHOR, ROADNARROWS LLC, OR ANY MEMBERS/EMPLOYEES
# OF ROADNARROW LLC OR DISTRIBUTORS OF THIS SOFTWARE BE LIABLE TO ANY
# PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
# DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
# EVEN IF THE AUTHORS OR ANY OF THE ABOVE PARTIES HAVE BEEN ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
#
# THE AUTHOR AND ROADNARROWS LLC SPECIFICALLY DISCLAIM ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN
# "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE NO OBLIGATION TO
# PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
#
################################################################################

_Cmd="prod_make_dist"

_Synopsis()
{

  printf "Usage: ${_Cmd} <prodroot>\n"
  printf "Make product distribution."
}

_Desc()
{
cat <<EOF

DESCRIPTION
  Make the files and tarballs for a product distribution. The distribution
  includes binaries, source, share, doc, etc.

OPTIONS
  -x <tbd>              Option TBD.
                        Default: xyz

  -?                    Display this help and exit.
EOF
}

# help
_help()
{
  _Synopsis
  _Desc
  exit 0
}

# error [msg1 [msg2...]]
_error()
{
  if [ $# -gt 0 ]
  then
    printf "${_Cmd}: Error: $1"
    shift
    while [ $# -gt 0 ]
    do
      printf ": $1" 
      shift
    done
    printf "\n"
  fi
  printf "Try '${_Cmd} -?' for more information.\n"
  exit 2
}

#defaults
prodroot=

# 
# Get options. Note: first colon says that getopts will not print errors.
#
while getopts :r: opt
do
  case $opt in
    x) _error "$OPTARG" "Unknown option."
        ;;

    # Usage option '-?' or bad option
    \?) if [ "$OPTARG" = "?" ]
        then
          _help
        else
          _error "$OPTARG" "Unknown option."
        fi
        ;;

    # Option requiring argument but none found
    \:)  _error "$OPTARG" "Required argument not specified." ;;
  esac
done

shift $(($OPTIND - 1))

prodroot="$1"

if [ "${prodroot}" = "" ]
then
  _error "prodroot" "no product root specified"
elif [ ! -d ${prodroot} ]
then
  _error "${prodroot}" "cannot access directory"
  exit 2
fi

prod=$(basename ${prodroot})
taboo='xinstall dist loc build .svn .deps obj *.log *.bak *.out *.pyc *.pyo'
tmpdir="${prodroot}/dist/tmp"
srcdir="${tmpdir}/${prod}"
taropts='--create --gzip --atime-preserve --verbose --file'

cppath()
{
  src=$1
  dstdir=$2
  if [ -d "${src}" ]
  then
    d=${dstdir}/${src}
    test -d ${d} || mkdir -p -m 775 ${d}
  else 
    d=${dstdir}/$(dirname ${src})
    test -d ${d} || mkdir -p -m 775 ${d}
    cp -p ${src} ${d}/.
  fi
}

make_src_tree()
{
  mkdir -p ${srcdir}
  prune=
  or=
  for pat in ${taboo}
  do
    prune="${prune} ${or} -name ${pat}"
    or="-or"
  done
  find . \( ${prune} \) -prune -or -print | \
  while read src
  do
    if [ -f ${src} ]
    then
      cppath ${src} ${srcdir}
    fi
  done
}

cd ${prodroot}

if [ -d ${srcdir} ]
then
  rm -fr "${srcdir}"
fi

make_src_tree

cd ${tmpdir}

tar ${taropts} ../${prod}-src.tar.gz ${prod}
