#!/bin/sh

# This script will create links, et c. after a package has been installed

set -e
# Automatically added by dh_installdocs
#if [ "$1" = "configure" ]; then
# if [ -d /usr/doc -a ! -e /usr/doc/parted -a -d /usr/share/doc/parted ]; then
#   ln -sf ../share/doc/parted /usr/doc/parted
# fi
#fi

#ADD ADDITIONAL TASKS HERE 
#  (e.g. adding a library dir to /etc/ld.so.conf.d/rnr.conf)
#  echo /usr/local/lib/rnr >> /etc/ld.so.conf.d/rnr.conf

ldconfig

ln -s /usr/local/share/Laelaps-@VERSION@ /usr/local/share/Laelaps
# End automatically added section
