######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 29 12:19:05 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += displaysysinfo.h getnode.h
FORMS += displaysysinfo.ui
SOURCES += displaysysinfo.cpp getnode.cpp main.cpp

CONFIG += qwt
