################################################################################
#
# install_h.mk
#
ifdef RNMAKE_DOXY
/*! 
\file 

\brief Auto-generate the install.h include file for the specific package
       architecture.

DEPRECATED.

\par Usage:
make pkgroot=\<dir\> install_h=\<file\> arch=\<arch\>
     bindir=\<bindir\> sbindir=\<sbindir\> libdir=\<libdir\>
     includedir=\<includedir\> sysconfdir=\<sysconfdir\> docdir=\<docdir\>
     mandir=\<mandir\> infodir=\<infodir\>

\pkgsynopsis
RN Make System

\pkgfile{install_h.mk}

\pkgauthor{Robin Knight,robin.knight@roadnarrows.com}

\pkgcopyright{2005-2018,RoadNarrows LLC,http://www.roadnarrows.com}

\license{MIT}

\EulaBegin
\EulaEnd

\cond RNMAKE_DOXY
 */
endif
#
################################################################################

_INSTALL_H_MK = 1

$(install_h):
	@echo ''
	@echo '     $@'
	@echo '//' > $@
	@echo '// File: $(notdir $@)' >> $@
	@echo '//' >> $@
	@echo '/*!' >> $@
	@echo	' * \\file' >> $@
	@echo	' *' >> $@
	@echo	' * \\brief Package installation information.' >> $@
	@echo	' *' >> $@
	@echo ' * \\par Architecture: ' >> $@
	@echo ' * $(arch)' >> $@
	@echo	' *' >> $@
	@echo ' * \warning Auto-generated by Rules.mk on' `date`>> $@
	@echo	' *' >> $@
	@echo ' * \\par Copyright:' >> $@
	@echo ' * \\n All Rights Reserved' >> $@
	@echo ' */' >> $@
	@echo '#ifndef _INSTALL_H' >> $@
	@echo '#define _INSTALL_H' >> $@
	@echo '' >> $@
	@echo '/*! \\brief package install bin directory*/'    							>> $@
	@echo '#define PKG_INSTALL_BINDIR      "$(bindir)"'     						>> $@
	@echo '' >> $@
	@echo '/*! \\brief package install system bin directory */' 				>> $@
	@echo '#define PKG_INSTALL_SBINDIR     "$(sbindir)"'    						>> $@
	@echo '' >> $@
	@echo '/*! \\brief package install include directory */'            >> $@
	@echo '#define PKG_INSTALL_INCDIR      "$(includedir)"' 						>> $@
	@echo '' >> $@
	@echo '/*! \\brief package library directory */'                		>> $@
	@echo '#define PKG_INSTALL_LIBDIR      "$(libdir)"'     					 	>> $@
	@echo '' >> $@
	@echo '/*! \\brief package install system configuration directory */'>> $@
	@echo '#define PKG_INSTALL_SYSCONFDIR  "$(sysconfdir)"' 						>> $@
	@echo '' >> $@
	@echo '/*! \\brief package install documentation directory */'      >> $@
	@echo '#define PKG_INSTALL_DOCDIR      "$(docdir)"'     						>> $@
	@echo '' >> $@
	@echo '/*! \\brief package install man pages directory */'          >> $@
	@echo '#define PKG_INSTALL_MANDIR      "$(mandir)"'     						>> $@
	@echo '' >> $@
	@echo '/*! \\brief package install information directory (s) */'    >> $@
	@echo '#define PKG_INSTALL_INFODIR     "$(infodir)"'    						>> $@
	@echo '' >> $@
	@echo '#endif // _INSTALL_H' >> $@

ifdef RNMAKE_DOXY
/*! \endcond RNMAKE_DOXY */
endif
