################################################################################
#
# Package: 	RN Make System
#
# File:			version_h.mk
#
ifdef RNMAKE_DOXY
/*! 
\file 

\brief Auto-generate the version.h include file for the package.

\par Usage:
make RNMAKE_PKG_ROOT=\<dir\> version_h=\<file\> pkg_mk=\<file\>

$LastChangedDate: 2009-07-09 15:53:24 -0600 (Thu, 09 Jul 2009) $
$Rev: 98 $

\par Description:

\author Robin Knight (robin.knight@roadnarrows.com)

\par Copyright:
(C) 2005-2009.  RoadNarrows LLC.
(http://www.roadnarrows.com)
\n All Rights Reserved

\cond RNMAKE_DOXY
 */
endif
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that
# (1) The above copyright notice and the following two paragraphs
# appear in all copies of the source code and (2) redistributions
# including binaries reproduces these notices in the supporting
# documentation.   Substantial modifications to this software may be
# copyrighted by their authors and need not follow the licensing terms
# described here, provided that the new terms are clearly indicated in
# all files where they apply.
#
# IN NO EVENT SHALL THE AUTHOR, ROADNARROWS LLC, OR ANY MEMBERS/EMPLOYEES
# OF ROADNARROW LLC OR DISTRIBUTORS OF THIS SOFTWARE BE LIABLE TO ANY
# PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
# DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
# EVEN IF THE AUTHORS OR ANY OF THE ABOVE PARTIES HAVE BEEN ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
#
# THE AUTHOR AND ROADNARROWS LLC SPECIFICALLY DISCLAIM ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN
# "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE NO OBLIGATION TO
# PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
#
################################################################################

include $(pkg_mk)

timestamp := $(shell date "+%Y.%m.%d %T")

$(version_h):
	@echo 'Auto-generating $@'
	@echo '//' > $@
	@echo '// File: $(notdir $@)' >> $@
	@echo '//' >> $@
	@echo '/*!' >> $@
	@echo	' * \\file' >> $@
	@echo	' *' >> $@
	@echo	' * \\brief Package version information.' >> $@
	@echo	' *' >> $@
	@echo ' * \\warning Auto-generated by Rules.mk on' `date`>> $@
	@echo	' *' >> $@
	@echo ' * \\par Copyright:' >> $@
	@echo ' * \\n All Rights Reserved' >> $@
	@echo ' */' >> $@
	@echo '#ifndef _VERSION_H' >> $@
	@echo '#define _VERSION_H' >> $@
	@echo '' >> $@
	@echo '#include "rnr/pkg.h"' >> $@
	@echo '' >> $@
	@echo '/*! \\brief package name */' 									 >> $@
	@echo '#define PKG_NAME       "$(PKG)"'                >> $@
	@echo '' >> $@
	@echo '/*! \\brief package dotted version */' 				 >> $@
	@echo '#define PKG_VERSION    "$(PKG_VERSION_DOTTED)"' >> $@
	@echo '' >> $@
	@echo '/*! \\brief package build date */' 						 >> $@
	@echo '#define PKG_TIMESTAMP  "$(timestamp)"'   			 >> $@
	@echo '' >> $@
	@echo '/*! \\brief package extended creation date */'  >> $@
	@echo '#define PKG_DATE       "$(PKG_VERSION_DATE)"'   >> $@
	@echo '' >> $@
	@echo '/*! \\brief package full name */' 							 >> $@
	@echo '#define PKG_FULL_NAME  "$(PKG_FULL_NAME)"'      >> $@
	@echo '' >> $@
	@echo '/*! \\brief package author(s) */'               >> $@
	@echo '#define PKG_AUTHORS    $(PKG_AUTHORS)'          >> $@
	@echo '' >> $@
	@echo '/*! \\brief package owner(s) */'                >> $@
	@echo '#define PKG_OWNERS     $(PKG_OWNERS)'           >> $@
	@echo '' >> $@
	@echo '/*! \\brief package legal disclaimer */'        >> $@
	@echo '#define PKG_DISCLAIMER $(PKG_DISCLAIMER)'       >> $@
	@echo '' >> $@
	@echo '/*! \\brief The package */'         >> $@
	@echo 'static const PkgInfo_T PkgInfo =' 	>> $@
	@echo '{'       													>> $@
	@echo '  PKG_NAME,' 											>> $@
	@echo '  PKG_VERSION,' 										>> $@
	@echo '  PKG_TIMESTAMP',									>> $@
	@echo '  PKG_DATE,' 											>> $@
	@echo '  PKG_FULL_NAME,' 									>> $@
	@echo '  PKG_AUTHORS,' 										>> $@
	@echo '  PKG_OWNERS,' 										>> $@
	@echo '  PKG_DISCLAIMER' 									>> $@
	@echo '};'       													>> $@
	@echo '' >> $@
	@echo '#endif // _VERSION_H' >> $@

ifdef RNMAKE_DOXY
/*! \endcond RNMAKE_DOXY */
endif
