#!/bin/bash
#
# File:
#   rnmake_all
#
# Usage:
#   rnmake_all
#
# Description:
#   Make clobber, deps, install for all active packages.
#

echo "rdk" ${0}
bindir=$(dirname $(realpath ${0}))
prefix=$(dirname ${bindir})

echo ${bindir} ", " ${prefix}

pkglist='librnr
  libserial i2c gpio
  netmsgs botsense 
  peripherals appkit
  odroid
  Dynamixel
  Hekateros Laelaps PanTilt Kuon Eudoxus'

echo $pkglist

declare -a pth

pth=("${prefix}/share/rnmake" "./share" "/usr/local/share/rnmake")

echo ${pth[*]}

exit 0
pkgroot='/prj/pkg'

for pkgname in ${pkglist}
do
  pkg="${pkgroot}/${pkgname}"
  if [[ ! -d ${pkg} ]]
  then
    continue
  fi
  cd ${pkg}
  echo
  echo "----------------------------------------------------------------------"
  echo " ${pkg}"
  echo "----------------------------------------------------------------------"
  make clobber; make deps; make install;
  cd -
done
