#!/bin/bash
#
# File:
#   rnsdk_ls_installed
#
# Usage:
#   rnsdk_ls_installed [OPTION]...
#   rnmake_all --help
#   ls_sdk_installed.sh [prefix]
#     prefix   {/prj | /usr/prefixal | <dir>}. DEFAULT: /prj
#
# Description:
#   Convenience script to pretty print all of the install RoadNarrows Robotics
#   SDK components.
#

argv0=$(basename $0)

# callHelp
callHelp()
{
  cat <<EOH
Usage: ${argv0} [OPTION]... [RNMAKEVAR]... [PKG]...
       ${argv0} --help

Convenience script to pretty print all of the install RoadNarrows Robotics SDK
components.

Options:
  --arch=ARCH         Installed architecture. Default: RNMAKE_ARCH_DFT.
  --no-color          Disable color output. Default: colors are enabled.
  --prefix=DIR        Installed prefix. Default: RNMAKE_INSTALL_PREFIX.
  --xprefix=DIR       Cross-installed prefix. Default RNMAKE_INSTALL_XPREFIX.

  --help              Print this help and exit.

Pretty-print (ls) installed RoadNarrows Robotics SDK files. The installled
directory prefix is determined as follows.
  1. \${prefix} if defined.
  2. \${xprefix}/\${arch} if defined.
  3. \${HOME}/xinstall/\${arch} if directory found.
  4. /usr/local
EOH
  exit 0;
}

# ansi colors
color_pre="\033["
color_post="\033[0m"
color_red="0;31m"
color_bold_red="1;31m"
color_green="0;32m"
color_yellow="0;33m"
color_bold_yellow="1;33m"
color_green="1;32m"
color_gray="1;30m"

# colors used
color_info="${color_pre}${color_green}"
color_warn="${color_pre}${color_yellow}"
color_error="${color_pre}${color_red}"
color_fatal="${color_pre}${color_bold_red}"
color_banner="${color_pre}${color_green}"
color_dir_banner="${color_pre}${color_gray}"
color_dir="${color_pre}${color_bold_yellow}"
color_end=${color_post}

# turnOffColor
turnOffColor()
{
  color_info=
  color_warn=
  color_error=
  color_fatal=
  color_banner=
  color_dir_banner=
  color_dir=
  color_end=
}

# showInfo msg [msg...]
showInfo()
{
  printf "${color_info}${*}${color_end}\n"
}

# showWarning wmsg [wmsg...]
showWarning()
{
  printf "${argv0}: ${color_warn}${*}${color_end}\n" >&2
}

# showError emsg [emsg...]
showError()
{
  printf "${argv0}: ${color_error}${*}${color_end}\n" >&2
}

# fatal exitcode emsg
fatal()
{
  printf "${argv0}: ${color_fatal}${2}${color_end}\n" >&2
  exit ${1}
}

# long and short options
longopts="arch:,no-color,prefix:,xprefix:,help"
shortopts=""

# get the options
OPTS=$(getopt --name ${argv0} -o "${shortopts}" --long "${longopts}" -- "${@}")

if [ $? != 0 ]
then
  fatal 2 "Try '${argv0} --help' for more information."
fi

#echo "${OPTS}"
eval set -- "${OPTS}"

# command line option and argument variables
rnmakeArch=${RNMAKE_ARCH_DFT}
rnmakePrefix=${RNMAKE_INSTALL_PREFIX}
rnmakeXPrefix=${RNMAKE_INSTALL_XPREFIX}
prefix=
lsopts="--color=always"

# process command-line options
while true
do
  case "$1" in
    --no-color)
        turnOffColor
        lsopts="--color=never"
        shift;;
    --arch)     rnmakeArch=$2; shift 2;;
    --prefix)   rnmakePrefix="$2"; shift 2;;
    --xprefix)  rnmakeXPrefix=$2; shift 2;;
    --help)     callHelp; shift;;

    --) shift; break;;
    *)  break;;
  esac
done

# default if not set
if [ -z "${rnmakeArch}" ]
then 
  rnmakeArch=x86_64
fi

# real install prefix
if [ ! -z "${rnmakePrefix}" ]
then
  prefix="${rnmakePrefix}"
elif [ ! -z "${rnmakeXPrefix}" ]
then
  prefix="${rnmakeXPrefix}/${rnmakeArch}"
elif [ -d "${HOME}/xinstall/${rnmakeArch}" ]
then
  prefix="${HOME}/xinstall/${rnmakeArch}"
else
  prefix="/usr/prefixal"
fi

if [ ! -d "${prefix}" ]
then
  fatal 8 "'${prefix}': Not a directory."
fi

bold_line='::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::' 
norm_line='~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~'

# showBanner prefix
showBanner()
{
	printf "\n${color_banner}${bold_line}\n"
  printf ":: ${1}\n"
	printf "${bold_line}${color_end}\n\n"
}

# showDirBanner dir
showDirBanner()
{
	printf "\n${color_dir_banner}${norm_line}\n"
  printf "~ ${1}\n"
	printf "${norm_line}${color_end}\n\n"
}

clear

showBanner ${prefix}

# lscolor dir
lscolor()
{
  if [ -d "${1}" ]
  then
    printf "  ${color_dir}${1}${color_end}\n"
    ls ${lsopts} $*
    printf "\n"
  fi
}

# install directories
bindir=${prefix}/bin
sbindir=${prefix}/sbin
libdir=${prefix}/lib
includedir=${prefix}/include
sysconfdir=${prefix}/etc
etcdir=/etc
sharedir=${prefix}/share


# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# include
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

showDirBanner ${includedir}

lscolor ${includedir}

lscolor ${includedir}/botsense
lscolor ${includedir}/botsense/plugins

lscolor ${includedir}/CogniBoost

lscolor ${includedir}/Dynamixel
lscolor ${includedir}/Dynamixel/dxl

lscolor ${includedir}/Hekateros

lscolor ${includedir}/Kuon

lscolor ${includedir}/Laelaps

lscolor ${includedir}/rnr
lscolor ${includedir}/rnr/appkit
lscolor ${includedir}/rnr/hid
lscolor ${includedir}/rnr/imu
lscolor ${includedir}/rnr/mot
lscolor ${includedir}/rnr/tinyxml


# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# lib
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

showDirBanner ${libdir}

lscolor ${libdir}

lscolor ${libdir}/botsense
lscolor ${libdir}/botsense/plugins

lscolor ${libdir}/cmake/rnr

lscolor ${libdir}/rnr

lscolor ${libdir}/python2.7/site-packages
lscolor ${libdir}/python2.7/site-packages/BotSense
lscolor ${libdir}/python2.7/site-packages/Eudoxus
lscolor ${libdir}/python2.7/site-packages/Hekateros
lscolor ${libdir}/python2.7/site-packages/Laelaps
lscolor ${libdir}/python2.7/site-packages/NetMsgs
lscolor ${libdir}/python2.7/site-packages/rnr


# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# share
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

showDirBanner ${sharedir}

lscolor ${sharedir}


# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# sysconf
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

showDirBanner ${sysconfdir}

lscolor ${sysconfdir}

lscolor ${sysconfdir}/eudoxus

lscolor ${sysconfdir}/hekateros

lscolor ${sysconfdir}/kuon

lscolor ${sysconfdir}/laelaps

lscolor ${sysconfdir}/pan_tilt

lscolor ${sysconfdir}/init.d
lscolor ${sysconfdir}/rc3.d
lscolor ${sysconfdir}/ld.so.conf.d
lscolor ${sysconfdir}/profile.d
lscolor ${sysconfdir}/udev/rules.d


# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# etc
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

showDirBanner ${etcdir}

lscolor ${etcdir}/eudoxus

lscolor ${etcdir}/hekateros

lscolor ${etcdir}/kuon

lscolor ${etcdir}/laelaps

lscolor ${etcdir}/pan_tilt

lscolor ${etcdir}/init.d
lscolor ${etcdir}/rc3.d
lscolor ${etcdir}/ld.so.conf.d
lscolor ${etcdir}/profile.d
lscolor ${etcdir}/udev/rules.d


# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# bin
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

showDirBanner ${bindir}

lscolor ${bindir}

