#!/bin/bash
#
# Script: hek_eecam_stop
#

## \file
##
## $LastChangedDate: 2013-09-24 16:56:04 +0000 (Tue, 24 Sep 2013) $  
## $Rev: 3325 $ 
## 
## \brief Stop end-to-end video streaming of Hekateros end effector camera.
##
## GSreamer pipeline.
##
## \author: Robin Knight (robin.knight@roadnarrows.com)
## 
## \par Copyright:
##   (C) 2015.  RoadNarrows LLC.
##   (http://www.roadnarrows.com)
##   All Rights Reserved

#
# @EulaBegin@
# @EulaEnd@
#

_Cmd="hek_eecam_stop"

_Synopsis="\
${_Cmd} [OPTION]...
       ${_Cmd} --help | -?
"

_Desc="\
Stop end-to-end video streaming of the Hekateros end effector camera.

If hek_eecam_stop is executed on a host different from the Hekateros, the
video stream over UDP will first be stop remotely on the source Hekateros.

For on-target Hekateros invocations, the video stream both originates and
terminates on the Hekateros. Note the a GUI is required to see the video.

OPTIONS
  -s, --src=HEK     The Hekateros network name or address to source the video. 
                      Default: Location of ROS master ROS_MASTER_URI.

      --help        Print this help.

NOTES
  o Remote command execution is done using the robot user id. This may require
    a password.
"

rosmaster="${ROS_MASTER_URI##http://}"
rosmaster="${rosmaster%%:*}"

# defaults
hekateros=${rosmaster}
hekusr=robot
host=$(/bin/hostname)
host=${host:-localhost}

# _usage [emsg1 [emsg2...]]
_usage()
{
  ec=0
  if [ $# -gt 0 ]
  then
    ec=2
    echo -n "${_Cmd}: $1" 1>&2
    shift
    while [ $# -gt 0 ]
    do
      echo -n ": $1"  1>&2
      shift
    done
    echo "\n" 1>&2
  fi
  echo "usage: ${_Synopsis}" 1>&2
  echo "${_Desc}" 1>&2
  exit ${ec}
}

opts=`getopt --long=src:,help --options=s: --name=${_Cmd} -- "$@"`

if [ $? != 0 ]
then
  _usage "Bad options."
  exit 1
fi

eval set -- "${opts}"

while true
do
  case "$1" in
    -s|--src) hekateros="$2"; shift 2;;
    --help) _usage; shift 1;;
    --) shift; break;;
    *) break;;
  esac
done

if [[ ${hekateros} = "" ]]
then
  echo "Cannot determine source Hekateros." 1>2
  exit 4
fi

if [[ "${hekateros}" = "${host}" || \
      "${hekateros}" = "localhost" || \
      "${hekateros}" = "127.0.1.1" || \
      "${hekateros}" = "127.0.0.1" ]]
then
  remote=false
else
  remote=true
fi

if [[ ${remote} = true ]]
then
  rcmd="{ \
export PATH=/prj/bin:/usr/local/bin:${PATH}; \
hek_eecam_kill
}"

  echo "Stopping Hekateros remote video streaming."

  ssh -f ${hekusr}@${hekateros} "${rcmd}"

  if [[ $? != 0 ]]
  then
    echo "Failed remote execution." 1>&2
  fi
fi

echo "Stopping any Hekateros local video streaming."
hek_eecam_kill
