#!/bin/bash
#
# Script: hek_service
#

## \file
##
## $LastChangedDate: 2013-09-25 09:39:14 -0600 (Wed, 25 Sep 2013) $  
## $Rev: 3338 $ 
## 
## \brief Hekateros services stop|start|restart|status convenience utility.
##
## Usage: hek_service stop|start|restart|status
##
## \author: Robin Knight (robin.knight@roadnarrows.com)
## 
## \par Copyright:
##   (C) 2014.  RoadNarrows LLC.
##   (http://www.roadnarrows.com)
##   All Rights Reserved

#
# @EulaBegin@
# @EulaEnd@
#

set -o nounset
#set -o errexit # failure is an option

# common environment
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin

readonly actions="stop|start|restart|status"
readonly upservices=("hek_bsproxy" "hek_roscore" "hek_control" "hek_xbox"
                    "hek_teleop")
readonly dnservices=("hek_teleop" "hek_xbox" "hek_control" "hek_roscore"
                    "hek_bsproxy")

usage()
{
  if [[ $# -gt 0 ]]
  then
    echo "$0: $@" 1>&2
  fi
  echo "usage: $0 {${actions}}" 1>&2
  exit 2
}

#
# exec_service action service...
#
exec_service()
{
  action="${1}"
  shift
  for src in "$@"
  do
    service "${src}" "${action}"
  done
}

if [[ $# -ne 1 ]]
then
  usage "no action specified"
fi

case "$1" in
  stop)     exec_service "$1" ${dnservices[@]};;
  start)    exec_service "$1" ${upservices[@]};;
  restart)  exec_service stop ${dnservices[@]}
            exec_service start ${upservices[@]};;
  status)   exec_service "$1" ${upservices[@]};;
  *) usage "$1" ": unknown action";;
esac

exit 0
