#!/bin/bash
#
# Script: hek_eecam_win
#

## \file
##
## $LastChangedDate: 2013-09-24 16:56:04 +0000 (Tue, 24 Sep 2013) $  
## $Rev: 3325 $ 
## 
## \brief Stream Hekateros end effector camera locally on Hekateros.
##
## GSreamer pipeline.
##
## Requires GUI interface to Hekateros.
##
## For the Creative USB 2.0 720p Camera, valid combinations are:
##  Name    Resolution   FPS
##  ----    ----------   ---
##  qvga    320x240      10 15 30
##  vga     640x480      10 15 30
##  720p    1280x720     10
##
## \author: Robin Knight (robin.knight@roadnarrows.com)
## 
## \par Copyright:
##   (C) 2015.  RoadNarrows LLC.
##   (http://www.roadnarrows.com)
##   All Rights Reserved

#
# @EulaBegin@
# @EulaEnd@
#

_Cmd="hek_eecam_win"

_Synopsis="\
${_Cmd} [OPTION]...
       ${_Cmd} --help | -?
"

_Desc="\
Stream the Hekateros end effector camera locally on Hekateros.

OPTIONS
  -r, --res=RES    Video resolution: One of qvga vga 720p WxH.
                    Default: vga
  -f, --fps=FPS    Frames per second.
                    Default: 15
  -t, --time       Add time stamped text overlay to video stream.
                    Default: false
      --help       Print help.
"

# defaults
width=640
height=480
fps=15
timeplugin=

viddev="/dev/$(readlink /dev/eecam)"

if [[ ! -c ${viddev} ]]
then 
  viddev="/dev/video0"
fi

# _usage [emsg1 [emsg2...]]
_usage()
{
  ec=0
  if [ $# -gt 0 ]
  then
    ec=2
    echo -n "${_Cmd}: $1" 1>&2
    shift
    while [ $# -gt 0 ]
    do
      echo -n ": $1"  1>&2
      shift
    done
    echo "\n" 1>&2
  fi
  echo "usage: ${_Synopsis}" 1>&2
  echo "${_Desc}" 1>&2
  exit ${ec}
}

opts=`getopt --long=res:,fps:,time,help --options=r:f:t --name=${_Cmd} -- "$@"`

if [ $? != 0 ]
then
  _usage "Bad options."
  exit 1
fi

eval set -- "${opts}"

while true
do
  case "$1" in
    -r|--res)
        res="$2";
        case "$res" in
          qvga) width=320; height=240;;
          vga)  width=640; height=480;;
          720p) width=1280; height=720;;
          *) width=${res%%x*}; height=${res##*x}
        esac
        shift 2;;
    -f|--fps)
      fps="$2"; shift 2;;
    -t|--time)
        timeplugin='! timeoverlay text="eecam" halignment=2 valignment=2'
        shift 1;;
    --help)
      _usage; shift 1;;
    --) shift; break;;
    *) break;;
  esac
done

# Uncomment to enable copious debugging messages.
#gstdbg='--gst-debug-level=3'

echo
echo "Streaming Hekateros End Effector camera video locally."
echo "  Video device:  ${viddev}"
echo "  Resolution:    ${width}x${height}"
echo "  Frames/second: ${fps}"
echo

#
# Simple video stream pipeline.
#
gst-launch-1.0 ${gstdbg} v4l2src name=eecam device=${viddev} \
  ! video/x-raw,width=${width},height=${height},framerate=${fps}/1 \
  ${timeplugin} \
  ! autovideosink
