#!/bin/sh
### BEGIN INIT INFO
# Provides:       hek_xbox
# Required-Start: $remote_fs $syslog
# Required-Stop:  $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: The xbox_360 ROS node
# Description:    The xbox_360 ROS node provides ROS services for a jacked-in
#                 Xbox360 (wireless) controller. The ROS node comes into and
#                 out of existence given the plugged-in state of a Xbox360
#                 controller.
### END INIT INFO

if [ -f /etc/profile.d/hekateros.sh ]
then
  . /etc/profile.d/hekateros.sh
elif [ -f /prj/etc/profile.d/hekateros.sh ]
then
  . /prj/etc/profile.d/hekateros.sh
fi

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin:/bin"

SERVICE=hek_xbox
ROSPKG=hid
ROSNODE=xbox_360

DAEMON=$(find_ros_node ${LD_LIBRARY_PATH} ${ROSPKG} ${ROSNODE})
PIDFILE=/var/run/${ROSNODE}.pid
LOGFILE=/var/log/${ROSNODE}.log

test -n "${DAEMON}" || exit 0
test -x "${DAEMON}" || exit 0

# standard init sh support functions
. /lib/lsb/init-functions

#
# Test if daemon is running.
#
is_daemon_running()
{
  /bin/ps -e | /bin/grep --quiet "${ROSNODE}" 2>/dev/null
  return $?
}

#
# Start service
#
startdaemon()
{
  if do_start_teleop
  then
    if ! is_daemon_running
    then
      log_daemon_msg "Starting Xbox360 ROS node" "${ROSNODE}" || true
      rm -f "${LOGFILE}"
      if start-stop-daemon --start --quiet --exec ${DAEMON} --pidfile ${PIDFILE} --make-pidfile --background -- --daemon --log-no-color --log=diag2 --logfile=${LOGFILE}
      then
        log_end_msg 0 || true
      else
        log_end_msg 1 || true
      fi
    else
      log_daemon_msg "Xbox360 ROS node already running" "" || true
      log_end_msg 1 || true
    fi

  else
    log_daemon_msg "Local on-target Xbox360 service disabled" "" || true
    log_end_msg 1 || true
  fi
}

#
# Stop service
#
stopdaemon()
{
  if is_daemon_running
  then
    log_daemon_msg "Stopping Xbox360 ROS node" "${ROSNODE}" || true
    if start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile ${PIDFILE} $@
    then
      #/bin/rm -f "${PIDFILE}"
      log_end_msg 0 || true
    else
      log_end_msg 1 || true
    fi
  else
    log_daemon_msg "Xbox360 ROS node not running" "" || true
    log_end_msg 1 || true
  fi
}

#
# Restart service
#
restartdaemon()
{
  stopdaemon
  startdaemon
}

#
# Status (not used)
#
pidof_daemon()
{
  if [ -e "${PIDFILE}" ]
  then
    PID=$(cat ${PIDFILE})
    pidof ${ROSNODE} | grep -q ${PID}
    return $?
  fi
  return 1
}

case $1 in
  start)
    startdaemon
    ;;
  stop)
    stopdaemon
    ;;
  restart)
    restartdaemon
    ;;
  reload|force-reload)
    ;;
  status)
	  status_of_proc -p "${PIDFILE}" "${DAEMON}" "${SERVICE}" && exit 0 || exit $?
    ;;
  *)
    log_action_msg "Usage: $0 {start|stop|restart|reload|force-reload|status}" || true
    exit 1
    ;;
esac

exit 0  # good
