#!/bin/sh
### BEGIN INIT INFO
# Provides:       kuon_teleop
# Required-Start: $remote_fs $syslog
# Required-Stop:  $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: The kuon_teleop ROS node
# Description:    The kuon_teleop ROS node provides Xbox360 teleoperation of
#                 the Kuon robotic mobile platform.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin

. /etc/profile.d/kuon.sh

ROSRUN=rosrun
ROSPKG=kuon_control
ROSNODE=kuon_teleop

DAEMON=`which ${ROSRUN}`
PIDFILE=/var/run/${ROSNODE}.pid
LOGFILE=/var/log/${ROSNODE}.log

test -x $DAEMON || exit 0

#
# Start service
#
startdaemon()
{
  echo -n "Starting ${ROSNODE} ROS node... "
  start-stop-daemon --start -x ${DAEMON} --pidfile ${PIDFILE} --make-pidfile --background -- ${ROSPKG} ${ROSNODE}
  echo "  done"
}

#
# Stop service
#
stopdaemon()
{
  echo -n "Stopping ${ROSNODE} ROS node... "
  start-stop-daemon --stop --pidfile ${PIDFILE}
  echo "done"
}

#
# Status
#
pidof_daemon() {
  if [ -e "${PIDFILE}" ]
  then
    PID=$(cat ${PIDFILE})
    pidof ${ROSNODE} | grep -q ${PID}
    return $?
  fi
  return 1
}

case $1 in
  start)
    startdaemon
    ;;
  stop)
    stopdaemon
    ;;
  restart|force-reload)
    $0 stop && sleep 2 && $0 start
    ;;
  status)
    if pidof_daemon
    then
      echo "${ROSNODE} running, process ${PID}"
    else
      echo "${ROSNODE} not running"
      if [ -e "${PIDFILE}" ]
      then
        exit 1  # program is dead and pid file exists.
      else
        exit 3  # program is not running
      fi
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0  # good
