#! /bin/sh
################################################################################
#
# Package:  RN Tool
#
# File:     pkgall
#
# Version:
#   $LastChangedDate$
#   $Rev$
#
# Description:
#   Execute command over the [sub]set of RN packages.
#
# Author: Robin Knight (robin.knight@roadnarrows.com)
#
# Copyright (C) 2010-2015.  RoadNarrows LLC.
# All Rights Reserved
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that
# (1) The above copyright notice and the following two paragraphs
# appear in all copies of the source code and (2) redistributions
# including binaries reproduces these notices in the supporting
# documentation.   Substantial modifications to this software may be
# copyrighted by their authors and need not follow the licensing terms
# described here, provided that the new terms are clearly indicated in
# all files where they apply.
#
# IN NO EVENT SHALL THE AUTHOR, ROADNARROWS LLC, OR ANY MEMBERS/EMPLOYEES
# OF ROADNARROW LLC OR DISTRIBUTORS OF THIS SOFTWARE BE LIABLE TO ANY
# PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
# DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
# EVEN IF THE AUTHORS OR ANY OF THE ABOVE PARTIES HAVE BEEN ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
#
# THE AUTHOR AND ROADNARROWS LLC SPECIFICALLY DISCLAIM ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN
# "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE NO OBLIGATION TO
# PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
#
################################################################################

_Cmd="pkgall"

# packages root directory
rootdir=/prj/pkg

# full list of packages (update when necessary)
pkglistfull="\
  rnmake \
  librnr \
  libserial \
  i2c \
  netmsgs \
  botsense \
  RoboSight \
  SkewlZone \
  Fusion \
"

_synopsis()
{
  echo "Usage: ${_Cmd} [--list=<pkglist>] [--without=<pkglist>] -- cmd arg..." >&2
  echo "Execute command over the [sub]set of RN packages." >&2
}

_desc()
{
cat >&2 <<EOF

DESCRIPTION
  Execute the specified command with arguments over a [sub]set of RN packages.
  Default package set is all RN packages.

OPTIONS
  -l, --list=<pkglist>     Alternate white-space separated package list.
  -w, --without=<pkglist>  Exclude packages white-space separated list.

  --help                   Display this help and exit.

ARGUMENTS
  cmd                      Command to execute over packages.
  arg ...                  Zero or more options and arguments to cmd.

DEFAULT PACKAGE LIST
EOF

for pkg in ${pkglistfull}
do
  echo -n " ${pkg}" >&2
done
echo >&2
}

# help
_help()
{
  _synopsis
  _desc
  exit 0
}

_try()
{
  echo "Try '${_Cmd} --help' for more information." >&2
}

# 
# Get options.
#

# defaults
pkglist="${pkglistfull}"
xlist=""
pkgcmd=""

export POSIXLY_CORRECT

DOOPTS=`getopt --long=without:,help --options=w: --name=${_Cmd} -- "$@"`

if [ $? != 0 ]
then
  _try
  exit 1
fi

eval set -- "${DOOPTS}"

while true
do
  case "$1" in
    -l|--list) pkglist="$2"; shift 2;;
    -w|--without) xlist="${xlist} $2"; shift 2;;
    --help) _help; shift;;
    --) shift; break;;
    *) echo "Internal error!"; exit 1;;
  esac
done

pkgcmd="${@}"
if [ "${pkgcmd}" = "" ]
then
  pkgcmd="echo"
fi

finallist=""
for pkg in ${pkglist}
do
  exclude=false
  for xpkg in ${xlist}
  do
    if [ "${xpkg}" = "${pkg}" ]
    then
      echo "${xpkg} = ${pkg}"
      exclude=true
      break
    fi
  done
  if [ $exclude = false ]
  then
    finallist="${finallist} ${pkg}"
  fi
done

echo "${finallist}"

for pkg in ${pkglistfull}
do
  echo ${pkg}
  svn status "${rootdir}/${pkg}"
done
