#!/bin/bash
#
# File:
#   rnmake_deb_all
#
# Usage:
#   rnmake_deb_all
#
# Description:
#   Make all debian development RoadNarrow SDK packages. Only packages that
#   support debian builds will be made
#

pkglist='librnr libserial i2c gpio appkit peripherals netmsgs botsense Dynamixel odroid Hekateros Laelaps PanTilt Eudoxus'

pkgroot='/prj/pkg'

for pkgname in ${pkglist}
do
  pkg="${pkgroot}/${pkgname}"
  if [[ ! -d ${pkg} ]]
  then
    continue
  fi
  cd ${pkg}
  echo
  echo "----------------------------------------------------------------------"
  echo " ${pkg}"
  echo "----------------------------------------------------------------------"
  make clobber; make deps; make install; make deb-pkg-dev
  cd -
done
