#!/bin/bash
#
# File:
#   rnmake_all
#
# Usage:
#   rnmake_all
#
# Description:
#   Make clobber, deps, install for all active packages.
#

pkglist='librnr libserial i2c gpio appkit peripherals netmsgs botsense Dynamixel odroid Hekateros Laelaps PanTilt Kuon Eudoxus'

pkgroot='/prj/pkg'

for pkgname in ${pkglist}
do
  pkg="${pkgroot}/${pkgname}"
  if [[ ! -d ${pkg} ]]
  then
    continue
  fi
  cd ${pkg}
  echo
  echo "----------------------------------------------------------------------"
  echo " ${pkg}"
  echo "----------------------------------------------------------------------"
  make clobber; make deps; make install;
  cd -
done
